### ISSUE TITLE
无法本地启动服务

### ISSUE THREAD

**Issue by olunx** [leancloud/spring-boot-getting-started#1]
按readme文件一步步走下来，通过lean up命令启动项目，并不能访问127.0.0.1:3000这个服务。只能访问127.0.0.1:8080，并且服务也不是正常的，这个还需要配置哪里吗？

**Comment by weakish** [comment]
建议直接用 [lean-cli] 初始化（选择 Java 环境），会自动配置。

我刚刚试了下，`lean up` 可以正常启动，端口也是对的。

[lean-cli]: https://leancloud.cn/docs/leanengine_cli.html

**Comment by weakish** [comment]
`lean up` 确实不可用，请按照 README 中的方法，使用 `local.sh` 启动应用。

**Comment by cmlanche** [comment]
LC_APP_ID 是什么？

**Comment by weakish** [comment]
LeanCloud 应用的 App ID，这些环境变量可以通过 `lean env` 查看。
