### ISSUE TITLE
请确保程序在 30 秒内正确地启动了 HTTP 服务

### ISSUE THREAD

**Issue by mz5210** [leancloud/spring-boot-getting-started#5]
[2020-11-17T06:48:14.398Z][system] 实例日志：[INFO] [main] INFO  Application - LeanEngine app init.
[INFO]   .   ____          _            __ _ _
[INFO]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[INFO] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[INFO]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[INFO]   '  |____| .__|_| |_|_| |_\__, | / / / /
[INFO]  =========|_|==============|___/=/_/_/_/
[INFO]  :: Spring Boot ::        (v1.4.3.RELEASE)
[INFO] 2020-11-17 06:47:59.287  INFO 21 --- [           main] cn.leancloud.demo.todo.Application       : Starting Application v0.0.1-SNAPSHOT on ff745e60c2e3 with PID 21 (/home/leanengine/app/target/spring-boot-getting-started-0.0.1-SNAPSHOT.jar started by leanengine in /home/leanengine/app)
[INFO] 2020-11-17 06:47:59.387  INFO 21 --- [           main] cn.leancloud.demo.todo.Application       : No active profile set, falling back to default profiles: default
[INFO] 2020-11-17 06:48:02.780  INFO 21 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@31b7dea0: startup date [Tue Nov 17 06:48:02 UTC 2020]; root of context hierarchy
[2020-11-17T06:48:14.399Z][system] 应用启动失败: 无法访问应用的 Web 端口（Error: connect ECONNREFUSED 10.101.40.3:41159），请确保程序在 30 秒内正确地启动了 HTTP 服务
[2020-11-17T06:48:15.524Z][system] 应用启动失败: 无法访问应用的 Web 端口（Error: connect ECONNREFUSED 10.101.40.3:41159），请确保程序在 30 秒内正确地启动了 HTTP 服务
[2020-11-17T06:48:15.526Z][system] 部署发生错误：发生了 1 个错误

**Comment by weakish** [comment]
Spring Boot 项目很难在免费的体验实例（只有 256 MB 内存）上跑起来，建议使用 512 MB 内存以上的标准实例测试（如果是正式的生产环境项目，推荐使用 1 GB 内存以上的标准实例）。
